version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Running React build..."
      - npm run build    # this produces 'dist' folder

artifacts:
  base-directory: dist    # <-- IMPORTANT: point to Vite output folder
  files:
    - '**/*'